name: hola-mundo
on: [push]
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Print user
        run: echo "This is the user ${{ github.actor }}"
      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run js file
        run: node greeting.js
